In [66]:
import pandas as pd

In [67]:
fighters = pd.read_csv(
    "../data/raw/kaggle_ufc_1994_2026/ufc_fighters_final.csv"
)

fights = pd.read_csv(
    "../data/raw/kaggle_ufc_1994_2026/ufc_gold_dataset_final.csv"
)

In [68]:
print("Fighters shape:", fighters.shape)
print("Fights shape:", fights.shape)

Fighters shape: (4455, 18)
Fights shape: (8551, 37)

In [69]:
fighters.head()

,Fighter_Name,Height,Weight,Reach,Stance,DOB,Wins,Losses,Draws,SLpM,Str_Acc,SApM,Str_Def,TD_Avg,TD_Acc,TD_Def,Sub_Avg,Fighter_URL
0,Tom Aaron,NaN,155 lbs.,NaN,NaN,1978-07-13,5,3,0,0.00,0%,0.00,0%,0.00,0%,0%,0.0,http://ufcstats.com/fighter-details/93fe7332d1...
1,Danny Abbadi,"5' 11""",155 lbs.,NaN,Orthodox,1983-07-03,4,6,0,3.29,38%,4.41,57%,0.00,0%,77%,0.0,http://ufcstats.com/fighter-details/15df64c02b...
2,Nariman Abbasov,"5' 8""",155 lbs.,"66.0""",Orthodox,1994-02-01,28,4,0,3.00,20%,5.67,46%,0.00,0%,66%,0.0,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion Abbey,"6' 2""",265 lbs.,"80.0""",Orthodox,1993-02-25,9,5,0,8.44,50%,14.06,28%,0.00,0%,0%,0.0,http://ufcstats.com/fighter-details/4961467134...
4,David Abbott,"6' 0""",265 lbs.,NaN,Switch,1965-04-26,10,15,0,1.35,30%,3.55,38%,1.07,33%,66%,0.0,http://ufcstats.com/fighter-details/b361180739...

In [70]:
fights.head()

,Fight_URL,Fighter_1,Fighter_2,Winner,Weight_Class,Method,End_Round,End_Time,Total_Fight_Time_Sec,Time_Format,...,F2_Body,F1_Leg,F2_Leg,F1_Distance,F2_Distance,F1_Clinch,F2_Clinch,F1_Ground,F2_Ground,Event_Date
0,http://ufcstats.com/fight-details/4acab67848e7...,Scott Morris,Sean Daugherty,Scott Morris,Open Weight Bout,Submission,1,0:20,20,No Time Limit,...,0,0,0,0,0,1,0,0,0,1994-03-11
1,http://ufcstats.com/fight-details/4b9ae533ccb3...,Patrick Smith,Ray Wizard,Patrick Smith,Open Weight Bout,Submission,1,0:58,58,No Time Limit,...,0,0,1,0,1,1,0,0,0,1994-03-11
2,http://ufcstats.com/fight-details/00835554f95f...,Royce Gracie,Patrick Smith,Royce Gracie,UFC 2 Tournament Title Bout,KO/TKO,1,1:17,77,No Time Limit,...,1,1,0,0,0,1,1,3,0,1994-03-11
3,http://ufcstats.com/fight-details/aa161c715974...,Royce Gracie,Remco Pardoel,Royce Gracie,Open Weight Bout,Submission,1,1:31,91,No Time Limit,...,0,0,0,0,0,0,0,0,0,1994-03-11
4,http://ufcstats.com/fight-details/8fbdde20b712...,Patrick Smith,Johnny Rhodes,Patrick Smith,Open Weight Bout,Submission,1,1:07,67,No Time Limit,...,0,2,2,3,4,2,0,0,0,1994-03-11

In [71]:
print("Fighter columns:")
print(fighters.columns.tolist())

print("\nFight columns:")
print(fights.columns.tolist())

Fighter columns:
['Fighter_Name', 'Height', 'Weight', 'Reach', 'Stance', 'DOB', 'Wins', 'Losses', 'Draws', 'SLpM', 'Str_Acc', 'SApM', 'Str_Def', 'TD_Avg', 'TD_Acc', 'TD_Def', 'Sub_Avg', 'Fighter_URL']

Fight columns:
['Fight_URL', 'Fighter_1', 'Fighter_2', 'Winner', 'Weight_Class', 'Method', 'End_Round', 'End_Time', 'Total_Fight_Time_Sec', 'Time_Format', 'F1_KD', 'F2_KD', 'F1_Sig_Landed', 'F1_Sig_Att', 'F2_Sig_Landed', 'F2_Sig_Att', 'F1_TD_Landed', 'F2_TD_Landed', 'F1_TD_Att', 'F2_TD_Att', 'F1_Sub_Att', 'F2_Sub_Att', 'F1_Ctrl_Sec', 'F2_Ctrl_Sec', 'F1_Head', 'F2_Head', 'F1_Body', 'F2_Body', 'F1_Leg', 'F2_Leg', 'F1_Distance', 'F2_Distance', 'F1_Clinch', 'F2_Clinch', 'F1_Ground', 'F2_Ground', 'Event_Date']

In [72]:
fighters.info()

<class 'pandas.DataFrame'>
RangeIndex: 4455 entries, 0 to 4454
Data columns (total 18 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Fighter_Name  4455 non-null   str
 1   Height        4137 non-null   str
 2   Weight        4369 non-null   str
 3   Reach         2515 non-null   str
 4   Stance        3606 non-null   str
 5   DOB           3949 non-null   str
 6   Wins          4455 non-null   int64
 7   Losses        4455 non-null   int64
 8   Draws         4455 non-null   int64
 9   SLpM          4455 non-null   float64
 10  Str_Acc       4455 non-null   str
 11  SApM          4455 non-null   float64
 12  Str_Def       4455 non-null   str
 13  TD_Avg        4455 non-null   float64
 14  TD_Acc        4455 non-null   str
 15  TD_Def        4455 non-null   str
 16  Sub_Avg       4455 non-null   float64
 17  Fighter_URL   4455 non-null   str
dtypes: float64(4), int64(3), str(11)
memory usage: 626.6 KB

In [73]:
fights.info()

<class 'pandas.DataFrame'>
RangeIndex: 8551 entries, 0 to 8550
Data columns (total 37 columns):
 #   Column                Non-Null Count  Dtype
---  ------                --------------  -----
 0   Fight_URL             8551 non-null   str
 1   Fighter_1             8551 non-null   str
 2   Fighter_2             8551 non-null   str
 3   Winner                8551 non-null   str
 4   Weight_Class          8551 non-null   str
 5   Method                8551 non-null   str
 6   End_Round             8551 non-null   int64
 7   End_Time              8551 non-null   str
 8   Total_Fight_Time_Sec  8551 non-null   int64
 9   Time_Format           8551 non-null   str
 10  F1_KD                 8551 non-null   int64
 11  F2_KD                 8551 non-null   int64
 12  F1_Sig_Landed         8551 non-null   int64
 13  F1_Sig_Att            8551 non-null   int64
 14  F2_Sig_Landed         8551 non-null   int64
 15  F2_Sig_Att            8551 non-null   int64
 16  F1_TD_Landed          8551 non-null   int64
 17  F2_TD_Landed          8551 non-null   int64
 18  F1_TD_Att             8551 non-null   int64
 19  F2_TD_Att             8551 non-null   int64
 20  F1_Sub_Att            8551 non-null   int64
 21  F2_Sub_Att            8551 non-null   int64
 22  F1_Ctrl_Sec           8551 non-null   int64
 23  F2_Ctrl_Sec           8551 non-null   int64
 24  F1_Head               8551 non-null   int64
 25  F2_Head               8551 non-null   int64
 26  F1_Body               8551 non-null   int64
 27  F2_Body               8551 non-null   int64
 28  F1_Leg                8551 non-null   int64
 29  F2_Leg                8551 non-null   int64
 30  F1_Distance           8551 non-null   int64
 31  F2_Distance           8551 non-null   int64
 32  F1_Clinch             8551 non-null   int64
 33  F2_Clinch             8551 non-null   int64
 34  F1_Ground             8551 non-null   int64
 35  F2_Ground             8551 non-null   int64
 36  Event_Date            8551 non-null   str
dtypes: int64(28), str(9)
memory usage: 2.4 MB

In [74]:
fighter_missing = pd.DataFrame({
    "missing_count": fighters.isna().sum(),
    "missing_percent": fighters.isna().mean() * 100
})

fighter_missing.sort_values("missing_percent", ascending=False)

              missing_count  missing_percent
Reach                  1940        43.546577
Stance                  849        19.057239
DOB                     506        11.358025
Height                  318         7.138047
Weight                   86         1.930415
Fighter_Name              0         0.000000
Str_Def                   0         0.000000
Sub_Avg                   0         0.000000
TD_Def                    0         0.000000
TD_Acc                    0         0.000000
TD_Avg                    0         0.000000
SLpM                      0         0.000000
SApM                      0         0.000000
Str_Acc                   0         0.000000
Draws                     0         0.000000
Losses                    0         0.000000
Wins                      0         0.000000
Fighter_URL               0         0.000000

In [75]:
numeric_stat_columns = [
    "SLpM",
    "SApM",
    "TD_Avg",
    "Sub_Avg",
]

percent_stat_columns = [
    "Str_Acc",
    "Str_Def",
    "TD_Acc",
    "TD_Def",
]

zero_counts = {}

for column in numeric_stat_columns:
    zero_counts[column] = (fighters[column] == 0).sum()

for column in percent_stat_columns:
    zero_counts[column] = (fighters[column] == "0%").sum()

zero_audit = pd.DataFrame.from_dict(
    zero_counts,
    orient="index",
    columns=["zero_count"],
)

zero_audit["zero_percent"] = (
    zero_audit["zero_count"] / len(fighters) * 100
)

zero_audit.sort_values("zero_percent", ascending=False)

         zero_count  zero_percent
Sub_Avg        2516     56.475870
TD_Avg         1856     41.661055
TD_Acc         1856     41.661055
TD_Def         1549     34.769921
SLpM            801     17.979798
Str_Acc         801     17.979798
Str_Def         734     16.475870
SApM            724     16.251403

In [76]:
fight_audit = fights.copy()

fight_audit["Event_Date"] = pd.to_datetime(
    fight_audit["Event_Date"]
)

fight_audit["Year"] = fight_audit["Event_Date"].dt.year

core_stat_columns = [
    "F1_KD",
    "F2_KD",
    "F1_Sig_Landed",
    "F1_Sig_Att",
    "F2_Sig_Landed",
    "F2_Sig_Att",
    "F1_TD_Landed",
    "F2_TD_Landed",
    "F1_TD_Att",
    "F2_TD_Att",
    "F1_Sub_Att",
    "F2_Sub_Att",
    "F1_Ctrl_Sec",
    "F2_Ctrl_Sec",
]

fight_audit["all_core_stats_zero"] = (
    fight_audit[core_stat_columns] == 0
).all(axis=1)

zero_stats_by_year = (
    fight_audit
    .groupby("Year")
    .agg(
        total_fights=("Fight_URL", "count"),
        all_zero_fights=("all_core_stats_zero", "sum"),
    )
)

zero_stats_by_year["zero_percent"] = (
    zero_stats_by_year["all_zero_fights"]
    / zero_stats_by_year["total_fights"]
    * 100
)

zero_stats_by_year

      total_fights  all_zero_fights  zero_percent
Year
1994            29                0           0.0
1995            34                0           0.0
1996            36                0           0.0
1997            39                0           0.0
1998            21                0           0.0
1999            44                0           0.0
2000            43                0           0.0
2001            40                0           0.0
2002            53                0           0.0
2003            41                0           0.0
2004            39                0           0.0
2005            80                0           0.0
2006           158                0           0.0
2007           171                0           0.0
2008           201                0           0.0
2009           215                0           0.0
2010           253                0           0.0
2011           300                0           0.0
2012           341                0           0.0
2013           386                0           0.0
2014           503                0           0.0
2015           473                0           0.0
2016           493                0           0.0
2017           457                0           0.0
2018           474                0           0.0
2019           516                0           0.0
2020           456                0           0.0
2021           509                0           0.0
2022           511                0           0.0
2023           520                0           0.0
2024           517                0           0.0
2025           522                0           0.0
2026            76                0           0.0

In [77]:
fight_audit["no_sig_strike_stats"] = (
    (fight_audit["F1_Sig_Att"] == 0)
    & (fight_audit["F2_Sig_Att"] == 0)
)

fight_audit["no_takedown_stats"] = (
    (fight_audit["F1_TD_Att"] == 0)
    & (fight_audit["F2_TD_Att"] == 0)
)

fight_audit["no_control_stats"] = (
    (fight_audit["F1_Ctrl_Sec"] == 0)
    & (fight_audit["F2_Ctrl_Sec"] == 0)
)

stats_by_year = (
    fight_audit
    .groupby("Year")
    .agg(
        total_fights=("Fight_URL", "count"),
        no_sig_strike_stats=("no_sig_strike_stats", "sum"),
        no_takedown_stats=("no_takedown_stats", "sum"),
        no_control_stats=("no_control_stats", "sum"),
    )
)

stats_by_year["no_sig_strike_percent"] = (
    stats_by_year["no_sig_strike_stats"]
    / stats_by_year["total_fights"]
    * 100
)

stats_by_year["no_takedown_percent"] = (
    stats_by_year["no_takedown_stats"]
    / stats_by_year["total_fights"]
    * 100
)

stats_by_year["no_control_percent"] = (
    stats_by_year["no_control_stats"]
    / stats_by_year["total_fights"]
    * 100
)

stats_by_year

,total_fights,no_sig_strike_stats,no_takedown_stats,no_control_stats,no_sig_strike_percent,no_takedown_percent,no_control_percent
Year,,,,,,,
1994,29,2,2,29,6.896552,6.896552,100.000000
1995,34,2,5,34,5.882353,14.705882,100.000000
1996,36,0,3,36,0.000000,8.333333,100.000000
1997,39,0,5,39,0.000000,12.820513,100.000000
1998,21,0,1,21,0.000000,4.761905,100.000000
1999,44,0,5,22,0.000000,11.363636,50.000000
2000,43,1,1,1,2.325581,2.325581,2.325581
2001,40,0,4,0,0.000000,10.000000,0.000000
2002,53,0,10,3,0.000000,18.867925,5.660377
2003,41,0,4,0,0.000000,9.756098,0.000000
2004,39,0,4,0,0.000000,10.256410,0.000000
2005,80,0,15,3,0.000000,18.750000,3.750000
2006,158,0,14,0,0.000000,8.860759,0.000000
2007,171,0,11,0,0.000000,6.432749,0.000000
2008,201,0,24,3,0.000000,11.940299,1.492537
2009,215,0,25,1,0.000000,11.627907,0.465116
2010,253,0,23,1,0.000000,9.090909,0.395257
2011,300,0,35,1,0.000000,11.666667,0.333333
2012,341,0,40,5,0.000000,11.730205,1.466276
2013,386,0,36,2,0.000000,9.326425,0.518135
2014,503,1,51,1,0.198807,10.139165,0.198807
2015,473,0,57,7,0.000000,12.050740,1.479915
2016,493,0,50,6,0.000000,10.141988,1.217039
2017,457,1,56,10,0.218818,12.253829,2.188184
2018,474,0,60,14,0.000000,12.658228,2.953586
2019,516,0,77,12,0.000000,14.922481,2.325581
2020,456,0,71,17,0.000000,15.570175,3.728070
2021,509,0,64,12,0.000000,12.573674,2.357564
2022,511,0,63,10,0.000000,12.328767,1.956947
2023,520,0,56,15,0.000000,10.769231,2.884615
2024,517,0,73,14,0.000000,14.119923,2.707930
2025,522,0,75,17,0.000000,14.367816,3.256705
2026,76,0,8,5,0.000000,10.526316,6.578947

In [78]:
fight_audit["has_any_control"] = (
    (fight_audit["F1_Ctrl_Sec"] > 0)
    | (fight_audit["F2_Ctrl_Sec"] > 0)
)

control_by_event = (
    fight_audit
    .groupby("Event_Date")
    .agg(
        total_fights=("Fight_URL", "count"),
        fights_with_control=("has_any_control", "sum"),
    )
    .reset_index()
)

control_by_event["control_signal_percent"] = (
    control_by_event["fights_with_control"]
    / control_by_event["total_fights"]
    * 100
)

In [79]:
control_by_event[
    (control_by_event["Event_Date"] >= "1998-01-01")
    & (control_by_event["Event_Date"] <= "2001-12-31")
]

   Event_Date  total_fights  fights_with_control  control_signal_percent
17 1998-03-13             6                    0                0.000000
18 1998-05-15             8                    0                0.000000
19 1998-10-16             7                    0                0.000000
20 1999-01-08             7                    0                0.000000
21 1999-03-05             7                    0                0.000000
22 1999-05-07             7                    0                0.000000
23 1999-07-16             8                    8              100.000000
24 1999-09-24             8                    7               87.500000
25 1999-11-19             7                    7              100.000000
26 2000-03-10             7                    7              100.000000
27 2000-04-14             6                    6              100.000000
28 2000-06-09             8                    8              100.000000
29 2000-09-22             8                    8              100.000000
30 2000-11-17             7                    6               85.714286
31 2000-12-16             7                    7              100.000000
32 2001-02-23             8                    8              100.000000
33 2001-05-04             8                    8              100.000000
34 2001-06-29             8                    8              100.000000
35 2001-09-28             8                    8              100.000000
36 2001-11-02             8                    8              100.000000

### Provisional finding: control-time coverage

Control-time values appear to have a structural coverage boundary around
July 16, 1999 (UFC 21). Earlier fights frequently contain zeros for both
fighters, which may represent unavailable data rather than true zero control.
This requires source validation before cleaning.

**Evidence:** All 7 fights from UFC 20 (1999-05-07) have zero control
time for both fighters, while all 8 fights from the immediately following
UFC 21 (1999-07-16) contain a positive control-time value for at least one
fighter.

**Working assumption:** Pre-UFC-21 control-time zeros represent unavailable
data rather than true zero control. Do not modify raw data; handle this later
during normalization/cleaning.

In [80]:
boundary_samples = fight_audit[
    fight_audit["Event_Date"].isin(
        [
            pd.Timestamp("1999-05-07"),
            pd.Timestamp("1999-07-16"),
        ]
    )
][
    [
        "Event_Date",
        "Fighter_1",
        "Fighter_2",
        "F1_Ctrl_Sec",
        "F2_Ctrl_Sec",
        "Fight_URL",
    ]
]

boundary_samples

,Event_Date,Fighter_1,Fighter_2,F1_Ctrl_Sec,F2_Ctrl_Sec,Fight_URL
173,1999-05-07,Ron Waterman,Chris Condo,0,0,http://ufcstats.com/fight-details/79f9086932f2...
174,1999-05-07,Laverne Clark,Fabiano Iha,0,0,http://ufcstats.com/fight-details/3a271d9d9210...
175,1999-05-07,Marcelo Mello,David Roberts,0,0,http://ufcstats.com/fight-details/6bb2a427004d...
176,1999-05-07,Wanderlei Silva,Tony Petarra,0,0,http://ufcstats.com/fight-details/c892b23ad8f2...
177,1999-05-07,Pete Williams,Travis Fulton,0,0,http://ufcstats.com/fight-details/a3fe8217502c...
178,1999-05-07,Pedro Rizzo,Tra Telligman,0,0,http://ufcstats.com/fight-details/99b5010fd259...
179,1999-05-07,Bas Rutten,Kevin Randleman,0,0,http://ufcstats.com/fight-details/73c07530f667...
180,1999-07-16,Maurice Smith,Marco Ruas,34,221,http://ufcstats.com/fight-details/62ac5bff3c18...
181,1999-07-16,Pat Miletich,Andre Pederneiras,96,4,http://ufcstats.com/fight-details/df8d4014d820...
182,1999-07-16,Jeremy Horn,Daiju Takase,178,0,http://ufcstats.com/fight-details/38e3986b7cff...
183,1999-07-16,Paul Jones,Flavio Luiz Moura,238,14,http://ufcstats.com/fight-details/82cf32aea3d7...
184,1999-07-16,Eugene Jackson,Royce Alger,20,153,http://ufcstats.com/fight-details/693e4a0bed9a...
185,1999-07-16,Andre Roberts,Ron Waterman,28,28,http://ufcstats.com/fight-details/c6f8541973f6...
186,1999-07-16,Travis Fulton,David Dodd,461,97,http://ufcstats.com/fight-details/1db8bed8b4d3...
187,1999-07-16,Tsuyoshi Kohsaka,Tim Lajcik,75,419,http://ufcstats.com/fight-details/3e4199f9a69b...

In [81]:
fighters["Fighter_URL"].duplicated().sum()

np.int64(0)

In [82]:
fights["Fight_URL"].duplicated().sum()

np.int64(0)

In [83]:
print("Earliest fight:", fight_audit["Event_Date"].min())
print("Latest fight:", fight_audit["Event_Date"].max())

Earliest fight: 1994-03-11 00:00:00
Latest fight: 2026-03-07 00:00:00

In [84]:
fight_fighters = set(fights["Fighter_1"]) | set(fights["Fighter_2"])
profile_fighters = set(fighters["Fighter_Name"])

missing_profiles = sorted(fight_fighters - profile_fighters)

print("Unique fighters appearing in fights:", len(fight_fighters))
print("Fighters in profile table:", len(profile_fighters))
print("Fight fighters missing a profile:", len(missing_profiles))

Unique fighters appearing in fights: 2647
Fighters in profile table: 4448
Fight fighters missing a profile: 0

In [85]:
missing_profiles[:20]

[]

In [86]:
duplicate_names = (
    fighters["Fighter_Name"]
    .value_counts()
    .loc[lambda counts: counts > 1]
)

duplicate_names

Fighter_Name
Mike Davis           2
Joey Gomez           2
Tony Johnson         2
Michael McDonald     2
Jean Silva           2
Bruno Silva          2
Victor Valenzuela    2
Name: count, dtype: int64

In [87]:
fighters[
    fighters["Fighter_Name"].isin(duplicate_names.index)
][
    [
        "Fighter_Name",
        "DOB",
        "Height",
        "Weight",
        "Fighter_URL",
    ]
].sort_values("Fighter_Name")

,Fighter_Name,DOB,Height,Weight,Fighter_URL
3698,Bruno Silva,1990-03-16,"5' 4""",125 lbs.,http://ufcstats.com/fighter-details/294aa73dbf...
3699,Bruno Silva,1989-07-13,"6' 0""",185 lbs.,http://ufcstats.com/fighter-details/12ebd7d157...
3684,Jean Silva,1977-10-08,"5' 6""",160 lbs.,http://ufcstats.com/fighter-details/9211aae062...
3709,Jean Silva,1996-12-27,"5' 7""",145 lbs.,http://ufcstats.com/fighter-details/52ef95b586...
1414,Joey Gomez,1986-07-21,"5' 10""",135 lbs.,http://ufcstats.com/fighter-details/0778f94eb5...
1416,Joey Gomez,1989-08-29,"5' 10""",155 lbs.,http://ufcstats.com/fighter-details/3a28e1e641...
2513,Michael McDonald,1965-02-06,"5' 11""",205 lbs.,http://ufcstats.com/fighter-details/d52ef69410...
2515,Michael McDonald,1991-01-15,"5' 9""",135 lbs.,http://ufcstats.com/fighter-details/d0314416a7...
882,Mike Davis,NaN,NaN,NaN,http://ufcstats.com/fighter-details/c8661e204c...
887,Mike Davis,1992-10-07,"6' 0""",155 lbs.,http://ufcstats.com/fighter-details/fb3e61720b...
1874,Tony Johnson,1983-05-02,"6' 2""",205 lbs.,http://ufcstats.com/fighter-details/3641a0d117...
1882,Tony Johnson,NaN,"6' 1""",265 lbs.,http://ufcstats.com/fighter-details/a45bab4995...
4120,Victor Valenzuela,NaN,"5' 10""",155 lbs.,http://ufcstats.com/fighter-details/de277a4abc...
4122,Victor Valenzuela,1994-02-09,"5' 9""",170 lbs.,http://ufcstats.com/fighter-details/078695e385...

In [88]:
profile_only_fighters = sorted(
    profile_fighters - fight_fighters
)

print("Profile-only fighters:", len(profile_only_fighters))

profile_only_fighters[:30]

Profile-only fighters: 1801

['AJ Fonseca',
 'AJ Matthews',
 'AJ McKee',
 'AJ Siscoe',
 'Aaron Ely',
 'Aaron Jeffery',
 'Aaron Lanfranco',
 'Aaron Miller',
 'Aaron Tau',
 'Aaron Trujillo',
 'Aaron Wetherspoon',
 'Abdellah Er-Ramy',
 'Abdul Azeem Badakhshi',
 'Abel Cullum',
 'Abongo Humphrey',
 'Abram Torres',
 'Acacio Dos Santos',
 'Achilles Estremadura',
 'Achmed Labasanov',
 'Adam Antolin',
 'Adam Bramhald',
 'Adam Hunter',
 'Adam Khaliev',
 'Adam Livingston',
 'Adam Lynn',
 'Adam Meredith',
 'Adam Piccolotti',
 'Adam Schindler',
 'Adam Smith',
 'Adam Steele']

In [89]:
duplicate_name_list = set(duplicate_names.index)

fight_rows_with_duplicate_names = fights[
    fights["Fighter_1"].isin(duplicate_name_list)
    | fights["Fighter_2"].isin(duplicate_name_list)
][
    [
        "Event_Date",
        "Fighter_1",
        "Fighter_2",
        "Weight_Class",
        "Fight_URL",
    ]
].sort_values("Event_Date")

fight_rows_with_duplicate_names

,Event_Date,Fighter_1,Fighter_2,Weight_Class,Fight_URL
1576,2011-03-26,Michael McDonald,Edwin Figueroa,Bantamweight Bout,http://ufcstats.com/fight-details/c67473192bda...
1597,2011-05-28,Michael McDonald,Chris Cariaso,Bantamweight Bout,http://ufcstats.com/fight-details/556952a9520d...
1755,2011-11-19,Michael McDonald,Alex Soto,Bantamweight Bout,http://ufcstats.com/fight-details/52f77a9f9eb6...
1884,2012-04-21,Miguel Torres,Michael McDonald,Bantamweight Bout,http://ufcstats.com/fight-details/33a93002fef6...
2171,2013-02-16,Renan Barao,Michael McDonald,UFC Interim Bantamweight Title Bout,http://ufcstats.com/fight-details/3dbf17b9946d...
2349,2013-08-17,Brad Pickett,Michael McDonald,Bantamweight Bout,http://ufcstats.com/fight-details/8e41d022b552...
2508,2013-12-14,Urijah Faber,Michael McDonald,Bantamweight Bout,http://ufcstats.com/fight-details/00566b4d8956...
3504,2016-01-02,Michael McDonald,Masanori Kanehara,Bantamweight Bout,http://ufcstats.com/fight-details/a19d619f1b9b...
3522,2016-01-17,Rob Font,Joey Gomez,Bantamweight Bout,http://ufcstats.com/fight-details/18cdc16fc7ab...
3735,2016-07-13,Michael McDonald,John Lineker,Bantamweight Bout,http://ufcstats.com/fight-details/08c6b88ac227...
3832,2016-09-17,Jose Quinonez,Joey Gomez,Bantamweight Bout,http://ufcstats.com/fight-details/187681b28431...
5078,2019-04-27,Gilbert Burns,Mike Davis,Lightweight Bout,http://ufcstats.com/fight-details/c2bcdcc47222...
5320,2019-10-05,Khalid Taha,Bruno Silva,Bantamweight Bout,http://ufcstats.com/fight-details/57ff0eb23519...
5333,2019-10-12,Mike Davis,Thomas Gifford,Lightweight Bout,http://ufcstats.com/fight-details/6a0217099efe...
5532,2020-03-14,Bruno Silva,David Dvorak,Flyweight Bout,http://ufcstats.com/fight-details/1a2d13834696...
5785,2020-10-10,Bruno Silva,Tagir Ulanbekov,Flyweight Bout,http://ufcstats.com/fight-details/dbb5d682a2d7...
5916,2021-01-20,Mike Davis,Mason Jones,Lightweight Bout,http://ufcstats.com/fight-details/031e6624f96a...
6011,2021-03-20,Bruno Silva,JP Buys,Flyweight Bout,http://ufcstats.com/fight-details/55bf7f19a132...
6097,2021-05-22,Bruno Silva,Victor Rodriguez,Flyweight Bout,http://ufcstats.com/fight-details/b381dc272b32...
6140,2021-06-19,Wellington Turman,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/bb1ac382e027...
6300,2021-10-16,Andrew Sanchez,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/fefa96b6d939...
6385,2021-12-11,Jordan Wright,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/9039762cb9f4...
6501,2022-03-12,Alex Pereira,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/226884e46a10...
6745,2022-08-13,Bruno Silva,Gerald Meerschaert,Middleweight Bout,http://ufcstats.com/fight-details/38b6ef176439...
6799,2022-10-01,Mike Davis,Viacheslav Borshchev,Lightweight Bout,http://ufcstats.com/fight-details/330506571d27...
7011,2023-03-11,Tyson Nam,Bruno Silva,Flyweight Bout,http://ufcstats.com/fight-details/c3af2b6ab126...
7066,2023-04-22,Brad Tavares,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/d00d5ef4ae0a...
7169,2023-06-24,Brendan Allen,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/9124740fe781...
7363,2023-10-21,Shara Magomedov,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/539732694ab2...
7444,2024-01-13,Westin Wilson,Jean Silva,Featherweight Bout,http://ufcstats.com/fight-details/0494ebcee93e...
7546,2024-03-16,Natan Levy,Mike Davis,Lightweight Bout,http://ufcstats.com/fight-details/4f20f3ada148...
7563,2024-03-30,Chris Weidman,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/77992b872738...
7708,2024-06-29,Charles Jourdain,Jean Silva,Featherweight Bout,http://ufcstats.com/fight-details/2b7883b304b3...
7712,2024-07-13,Drew Dober,Jean Silva,Lightweight Bout,http://ufcstats.com/fight-details/54de03e04f57...
7725,2024-07-20,Cody Durden,Bruno Silva,Flyweight Bout,http://ufcstats.com/fight-details/94541dd979e0...
7871,2024-10-26,Ismail Naurdiev,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/bde635a4f345...
7942,2024-12-14,Manel Kape,Bruno Silva,Flyweight Bout,http://ufcstats.com/fight-details/1a635a5e4551...
7983,2025-02-01,Fares Ziam,Mike Davis,Lightweight Bout,http://ufcstats.com/fight-details/775788423f5e...
8019,2025-02-22,Jean Silva,Melsik Baghdasaryan,Featherweight Bout,http://ufcstats.com/fight-details/8ef7723b6a8b...
8102,2025-04-12,Bryce Mitchell,Jean Silva,Featherweight Bout,http://ufcstats.com/fight-details/8c540eb4afe8...
8144,2025-05-10,Marc-Andre Barriault,Bruno Silva,Middleweight Bout,http://ufcstats.com/fight-details/6ecfa439ef90...
8173,2025-06-07,Bruno Silva,Joshua Van,Flyweight Bout,http://ufcstats.com/fight-details/b6a87389bdc3...
8226,2025-07-12,Mitch Ramirez,Mike Davis,Lightweight Bout,http://ufcstats.com/fight-details/7f33fbdc35af...
8319,2025-09-13,Diego Lopes,Jean Silva,Featherweight Bout,http://ufcstats.com/fight-details/de1a3734be60...
8377,2025-10-18,Bruno Silva,HyunSung Park,Flyweight Bout,http://ufcstats.com/fight-details/668a44403a13...
8478,2026-01-24,Arnold Allen,Jean Silva,Featherweight Bout,http://ufcstats.com/fight-details/836a188a90e4...

### Fighter identity finding

`Fighter_Name` is not globally unique. Seven names occur for multiple
distinct fighter profiles, each with a unique `Fighter_URL`.

Some ambiguous names also appear in the fight table, meaning fighter names
cannot safely serve as permanent join keys.

UPSET should eventually use its own internal fighter ID and maintain
source-specific IDs for reconciliation across data providers.

## Profile-Only Fighter Investigation

The fighter profile dataset contains 1,801 names that do not appear in the historical fight dataset.

The goal of this section is not to delete these fighters. We want to briefly investigate why the profile dataset has broader coverage than the fight dataset and determine what role these records should have in UPSET.

In [90]:
# Collect every fighter name that appears in the historical fight table.
fight_fighter_names = set(fights["Fighter_1"].dropna()) | set(
    fights["Fighter_2"].dropna()
)

# Select fighter profiles whose names never appear in either fight column.
profile_only = fighters[
    ~fighters["Fighter_Name"].isin(fight_fighter_names)
].copy()

print(f"Profile-only fighter rows: {len(profile_only):,}")
print()

profile_only[
    [
        "Fighter_Name",
        "Weight",
        "Wins",
        "Losses",
        "Draws",
        "Fighter_URL",
    ]
].head(25)

Profile-only fighter rows: 1,803

,Fighter_Name,Weight,Wins,Losses,Draws,Fighter_URL
0,Tom Aaron,155 lbs.,5,3,0,http://ufcstats.com/fighter-details/93fe7332d1...
2,Nariman Abbasov,155 lbs.,28,4,0,http://ufcstats.com/fighter-details/59a9d6dac6...
3,Darion Abbey,265 lbs.,9,5,0,http://ufcstats.com/fighter-details/4961467134...
8,Hiroyuki Abe,145 lbs.,8,15,3,http://ufcstats.com/fighter-details/c0ed7b2081...
13,Cyborg Abreu,NaN,0,0,0,http://ufcstats.com/fighter-details/f689bd7bbd...
14,Daniel Acacio,180 lbs.,30,18,0,http://ufcstats.com/fighter-details/1c5879330d...
15,John Adajar,170 lbs.,6,2,0,http://ufcstats.com/fighter-details/989b85f654...
18,Anthony Adams,185 lbs.,8,2,0,http://ufcstats.com/fighter-details/a77633a989...
22,Mohamed Ado,170 lbs.,5,1,0,http://ufcstats.com/fighter-details/7a846fcbf1...
25,Kantharaj Agasa,135 lbs.,12,3,0,http://ufcstats.com/fighter-details/26f4288e83...
27,Fabio Aguiar,185 lbs.,17,1,0,http://ufcstats.com/fighter-details/501821d7fb...
28,Edwin Aguilar,185 lbs.,26,19,0,http://ufcstats.com/fighter-details/6cadc0a0ba...
34,Agulali,125 lbs.,13,2,0,http://ufcstats.com/fighter-details/b2efa582ad...
35,Ahejiang Ailinuer,145 lbs.,15,3,0,http://ufcstats.com/fighter-details/ff584c17bc...
36,Mike Aina,155 lbs.,14,6,1,http://ufcstats.com/fighter-details/9e3dbb9c68...
37,Ashiek Ajim,135 lbs.,6,2,0,http://ufcstats.com/fighter-details/49dea784f6...
38,Hitomi Akano,135 lbs.,18,10,0,http://ufcstats.com/fighter-details/2eada40ac8...
45,Herdem Alacabek,205 lbs.,5,1,0,http://ufcstats.com/fighter-details/7578cc6bd7...
46,Javi Alanis,135 lbs.,0,4,0,http://ufcstats.com/fighter-details/2144954270...
49,Brett Albee,225 lbs.,3,2,0,http://ufcstats.com/fighter-details/9b28292abe...
54,Israel Albuquerque,185 lbs.,0,3,0,http://ufcstats.com/fighter-details/dd1b90eea0...
55,Juan Alcain,NaN,1,2,0,http://ufcstats.com/fighter-details/39f62b833e...
62,Jose Alday,135 lbs.,14,6,1,http://ufcstats.com/fighter-details/7460ddef98...
70,Kenneth Alexander,155 lbs.,7,6,0,http://ufcstats.com/fighter-details/8fd76e1b49...
73,Olaf Alfonso,170 lbs.,8,12,0,http://ufcstats.com/fighter-details/b757c73f44...

In [91]:
profile_only["Fighter_URL"].str.extract(
    r"https?://([^/]+)",
    expand=False,
).value_counts()

Fighter_URL
ufcstats.com    1803
Name: count, dtype: int64

In [92]:
print(f"Profile-only rows: {len(profile_only):,}")
print(f"Profile-only unique names: {profile_only['Fighter_Name'].nunique():,}")
print()

profile_only[
    profile_only["Fighter_Name"].duplicated(keep=False)
][
    [
        "Fighter_Name",
        "DOB",
        "Height",
        "Weight",
        "Fighter_URL",
    ]
].sort_values("Fighter_Name")

Profile-only rows: 1,803
Profile-only unique names: 1,801

,Fighter_Name,DOB,Height,Weight,Fighter_URL
1874,Tony Johnson,1983-05-02,"6' 2""",205 lbs.,http://ufcstats.com/fighter-details/3641a0d117...
1882,Tony Johnson,NaN,"6' 1""",265 lbs.,http://ufcstats.com/fighter-details/a45bab4995...
4120,Victor Valenzuela,NaN,"5' 10""",155 lbs.,http://ufcstats.com/fighter-details/de277a4abc...
4122,Victor Valenzuela,1994-02-09,"5' 9""",170 lbs.,http://ufcstats.com/fighter-details/078695e385...

### Profile-Only Fighter Conclusion

The fighter profile dataset contains 1,803 profile-only rows representing 1,801 unique names.

The row/name difference is caused by two duplicate-name identity pairs:
- Tony Johnson
- Victor Valenzuela

All profile-only records use `ufcstats.com` fighter URLs.

External validation suggests that UFCStats' fighter directory has broader scope than the historical UFC fight dataset. Some profileonly fighters have records from UFC adjacent or other promotions such as DWCS, Strikeforce, and ProElite.

Therefore, profile-only fighters should not be treated as invalid records or deleted.

Working conclusion:

- the fighter profile table has broader coverage than the fight table
- the fight table should define the historical UFC fight universe for this dataset
- fighter profiles may still be useful for identity resolution, enrichment, and future analysis
- filtering should happen for a specific analytical purpose rather than by deleting profile-only fighters globally

## Cito API Validation

We are beginning evaluation of Cito as a secondary/current UFC data source.

The first validation step compares one fighter available in both Cito and the historical Kaggle fighter table.

We are using Islam Makhachev as the initial overlap example.

In [93]:
islam_kaggle = fighters[
    fighters["Fighter_Name"] == "Islam Makhachev"
]

islam_kaggle[
    [
        "Fighter_Name",
        "Height",
        "Weight",
        "Reach",
        "Stance",
        "Wins",
        "Losses",
        "Draws",
        "SLpM",
        "SApM",
        "TD_Avg",
        "TD_Acc",
        "TD_Def",
        "Sub_Avg",
        "Fighter_URL",
    ]
]

,Fighter_Name,Height,Weight,Reach,Stance,Wins,Losses,Draws,SLpM,SApM,TD_Avg,TD_Acc,TD_Def,Sub_Avg,Fighter_URL
2387,Islam Makhachev,"5' 10""",170 lbs.,"70.0""",Southpaw,28,1,0,2.45,1.45,3.1,56%,91%,1.0,http://ufcstats.com/fighter-details/275aca31f6...

In [94]:
cito_islam = {
    "Fighter_Name": "Islam Makhachev",
    "Height": '5\' 10"',
    "Weight": "170 lbs.",
    "Reach": '70.5"',
    "Stance": "Southpaw",
    "Wins": 29,
    "Losses": 1,
    "Draws": 0,
    "SLpM": 2.27,
    "SApM": 1.42,
    "TD_Avg": 3.22,
    "TD_Acc": 54.55,
    "TD_Def": 91,
    "Sub_Avg": 0.87,
}

kaggle_islam = islam_kaggle.iloc[0]

comparison = pd.DataFrame({
    "Kaggle": {
        "Height": kaggle_islam["Height"],
        "Weight": kaggle_islam["Weight"],
        "Reach": kaggle_islam["Reach"],
        "Stance": kaggle_islam["Stance"],
        "Wins": kaggle_islam["Wins"],
        "Losses": kaggle_islam["Losses"],
        "SLpM": kaggle_islam["SLpM"],
        "SApM": kaggle_islam["SApM"],
        "TD_Avg": kaggle_islam["TD_Avg"],
        "TD_Acc": kaggle_islam["TD_Acc"],
        "TD_Def": kaggle_islam["TD_Def"],
        "Sub_Avg": kaggle_islam["Sub_Avg"],
    },
    "Cito": {
        "Height": cito_islam["Height"],
        "Weight": cito_islam["Weight"],
        "Reach": cito_islam["Reach"],
        "Stance": cito_islam["Stance"],
        "Wins": cito_islam["Wins"],
        "Losses": cito_islam["Losses"],
        "SLpM": cito_islam["SLpM"],
        "SApM": cito_islam["SApM"],
        "TD_Avg": cito_islam["TD_Avg"],
        "TD_Acc": f"{cito_islam['TD_Acc']}%",
        "TD_Def": f"{cito_islam['TD_Def']}%",
        "Sub_Avg": cito_islam["Sub_Avg"],
    },
})

comparison

           Kaggle      Cito
Height     5' 10"    5' 10"
Weight   170 lbs.  170 lbs.
Reach       70.0"     70.5"
Stance   Southpaw  Southpaw
Wins           28        29
Losses          1         1
SLpM         2.45      2.27
SApM         1.45      1.42
TD_Avg        3.1      3.22
TD_Acc        56%    54.55%
TD_Def        91%       91%
Sub_Avg       1.0      0.87

In [95]:
import os
from pathlib import Path

import requests
from dotenv import load_dotenv

# Find the project root whether VS Code runs the notebook
# from /upset or /upset/notebooks.
current_dir = Path.cwd()
project_root = (
    current_dir.parent
    if current_dir.name == "notebooks"
    else current_dir
)

# Load secrets from the local .env file.
load_dotenv(project_root / ".env")

cito_api_key = os.getenv("CITO_API_KEY")

if not cito_api_key:
    raise RuntimeError("CITO_API_KEY was not found in .env")

url = "https://api.citoapi.com/api/v1/ufc/search"

response = requests.get(
    url,
    params={"q": "islam"},
    headers={"x-api-key": cito_api_key},
    timeout=30,
)

print("HTTP status:", response.status_code)

HTTP status: 200

In [96]:
# Convert the JSON response into normal Python objects.
cito_data = response.json()

# The search endpoint can return multiple fighters.
cito_fighters = cito_data["data"]["fighters"]

print(f"Fighters returned: {len(cito_fighters)}")

for fighter in cito_fighters:
    print(fighter["name"])

Fighters returned: 2
Islam Makhachev
Islam Dulatov

In [97]:
cito_islam = next(
    fighter
    for fighter in cito_fighters
    if fighter["name"] == "Islam Makhachev"
)

print("ID:", cito_islam["id"])
print("Name:", cito_islam["name"])
print("Record:", cito_islam["recordText"])
print("Reach:", cito_islam["reachInches"])

ID: 2df4f188-a33e-463a-a66b-471cfa23e2a0
Name: Islam Makhachev
Record: 29-1-0 (W-L-D)
Reach: 70.5

In [98]:
cito_stats = cito_islam["stats"]

comparison_live = pd.DataFrame({
    "Kaggle": {
        "Height": kaggle_islam["Height"],
        "Weight": kaggle_islam["Weight"],
        "Reach": kaggle_islam["Reach"],
        "Stance": kaggle_islam["Stance"],
        "Wins": kaggle_islam["Wins"],
        "Losses": kaggle_islam["Losses"],
        "SLpM": kaggle_islam["SLpM"],
        "SApM": kaggle_islam["SApM"],
        "TD_Avg": kaggle_islam["TD_Avg"],
        "TD_Acc": kaggle_islam["TD_Acc"],
        "TD_Def": kaggle_islam["TD_Def"],
        "Sub_Avg": kaggle_islam["Sub_Avg"],
    },
    "Cito": {
        "Height": f'{int(cito_islam["heightInches"]) // 12}\' '
                  f'{int(cito_islam["heightInches"]) % 12}"',
        "Weight": f'{cito_islam["weightLbs"]} lbs.',
        "Reach": f'{cito_islam["reachInches"]}"',
        "Stance": cito_islam["stance"],
        "Wins": cito_islam["recordWins"],
        "Losses": cito_islam["recordLosses"],
        "SLpM": cito_stats["sigStrikesLandedPerMin"],
        "SApM": cito_stats["sigStrikesAbsorbedPerMin"],
        "TD_Avg": cito_stats["takedownAvgPer15Min"],
        "TD_Acc": f'{float(cito_stats["takedownAccuracy"]) * 100:.2f}%',
        "TD_Def": f'{float(cito_stats["takedownDefense"]) * 100:.0f}%',
        "Sub_Avg": cito_stats["submissionAvgPer15Min"],
    },
})

comparison_live

           Kaggle      Cito
Height     5' 10"    5' 10"
Weight   170 lbs.  170 lbs.
Reach       70.0"     70.5"
Stance   Southpaw  Southpaw
Wins           28        29
Losses          1         1
SLpM         2.45      2.27
SApM         1.45      1.42
TD_Avg        3.1      3.22
TD_Acc        56%    54.55%
TD_Def        91%       91%
Sub_Avg       1.0      0.87

In [99]:
# Find the UFC 302 bout from the search response we already downloaded.
poirier_bout = next(
    bout
    for bout in cito_data["data"]["bouts"]
    if bout["eventSlug"] == "ufc-302-makhachev-vs-poirier"
)

bout_id = poirier_bout["id"]

print("Bout ID:", bout_id)
print(
    "Fight:",
    poirier_bout["fighters"][0]["fighterName"],
    "vs",
    poirier_bout["fighters"][1]["fighterName"],
)
print("Result:", poirier_bout["method"])
print("Finish:", f'Round {poirier_bout["resultRound"]} at {poirier_bout["resultTime"]}')

Bout ID: 1a0031e2072f21b6
Fight: Dustin Poirier vs Islam Makhachev
Result: SUB
Finish: Round 5 at 2:42

In [100]:
rounds_url = (
    f"https://api.citoapi.com/api/v1/ufc/bouts/{bout_id}/rounds"
)

rounds_response = requests.get(
    rounds_url,
    headers={"x-api-key": cito_api_key},
    timeout=30,
)

print("HTTP status:", rounds_response.status_code)

HTTP status: 403

In [101]:
recent_response = requests.get(
    "https://api.citoapi.com/api/v1/ufc/events/recent",
    headers={"x-api-key": cito_api_key},
    timeout=30,
)

print("HTTP status:", recent_response.status_code)

recent_data = recent_response.json()

for event in recent_data["data"][:5]:
    print(
        event.get("eventDate"),
        "-",
        event.get("title"),
        "- hasStats:",
        event.get("hasStats"),
    )

HTTP status: 200
2026-09-15 - Dana White's Contender Series 10.6 - hasStats: False
2026-09-12 - Noche UFC - hasStats: True
2026-09-08 - Dana White's Contender Series 10.5 - hasStats: False
2026-09-05 - UFC Fight Night: Hooker vs Parnasse - hasStats: True
2026-09-01 - Dana White's Contender Series 10.4 - hasStats: False

In [102]:
recent_event = next(
    event
    for event in recent_data["data"]
    if event.get("hasStats")
)

print("Event:", recent_event["title"])
print("Date:", recent_event["eventDate"])
print("Slug:", recent_event["slug"])

Event: Noche UFC
Date: 2026-09-12
Slug: ufc-fight-night-september-12-2026

In [103]:
event_slug = recent_event["slug"]

bouts_response = requests.get(
    f"https://api.citoapi.com/api/v1/ufc/events/{event_slug}/bouts",
    headers={"x-api-key": cito_api_key},
    timeout=30,
)

print("HTTP status:", bouts_response.status_code)

bouts_data = bouts_response.json()

HTTP status: 200

In [104]:
for bout in bouts_data["data"]:
    fighter_names = [
        fighter["fighterName"]
        for fighter in bout["fighters"]
    ]

    print(
        bout["id"],
        "-",
        " vs ".join(fighter_names),
        "-",
        bout["method"],
    )

13008 - Jose Miguel Delgado vs Jean Silva - Submission
12977 - Joseph Morales vs Brandon Moreno - Decision - Split
fight-night-september-12-2026-marwan-rahiki-tommy-mcmillen - Marwan Rahiki vs Tommy McMillen - Decision - Unanimous
12976 - Alexa Grasso vs Manon Fiorot - Decision - Unanimous
12975 - Curtis Blaydes vs Waldo Cortes Acosta - Decision - Unanimous
13000 - Dan Ige vs David Martinez - Decision - Unanimous
12978 - Edgar Chairez vs Tim Elliott - Decision - Unanimous
13001 - Muslim Salikhov vs Ignacio Bahamondes - Decision - Unanimous
12979 - Djorden Santos vs Yousri Belgaroui - KO/TKO
13118 - Tommy Gantt vs Drakkar Klose - Submission
fight-night-september-12-2026-rafa-garcia-zhu-rong - Rongzhu vs Rafa Garcia - Decision - Unanimous
13119 - Jessie Rosas vs Sean King III - KO/TKO
12980 - Regina Tarin vs JJ Aldrich - Decision - Unanimous

In [105]:
test_bout_id = "12975"

rounds_response = requests.get(
    f"https://api.citoapi.com/api/v1/ufc/bouts/{test_bout_id}/rounds",
    headers={"x-api-key": cito_api_key},
    timeout=30,
)

print("HTTP status:", rounds_response.status_code)

HTTP status: 200

In [106]:
rounds_data = rounds_response.json()

print(rounds_data.keys())
print(type(rounds_data["data"]))
print("Rows returned:", len(rounds_data["data"]))

dict_keys(['success', 'data', 'meta'])
<class 'list'>
Rows returned: 6

In [107]:
rounds_data["data"][0]

{'id': 'e5dfafc4-b92e-40fc-b955-ebeb0f310cff',
 'boutId': '12975',
 'fighterSlug': 'curtis-blaydes',
 'fighterName': 'Curtis Blaydes',
 'round': 1,
 'knockdowns': 0,
 'significantStrikes': '7 of 27',
 'totalStrikes': '7 of 27',
 'takedowns': '1 of 3',
 'submissionAttempts': 0,
 'reversals': 0,
 'controlTime': '1:13',
 'head': '1 of 20',
 'body': '2 of 2',
 'leg': '4 of 5',
 'distance': '6 of 26',
 'clinch': '0 of 0',
 'ground': '1 of 1',
 'lastSyncedAt': '2026-09-12T22:57:42.270Z'}

In [108]:
round_stats_df = pd.DataFrame(rounds_data["data"])

round_stats_df[
    [
        "fighterName",
        "round",
        "knockdowns",
        "significantStrikes",
        "totalStrikes",
        "takedowns",
        "submissionAttempts",
        "controlTime",
        "head",
        "body",
        "leg",
        "distance",
        "clinch",
        "ground",
    ]
]

,fighterName,round,knockdowns,significantStrikes,totalStrikes,takedowns,submissionAttempts,controlTime,head,body,leg,distance,clinch,ground
0,Curtis Blaydes,1,0,7 of 27,7 of 27,1 of 3,0,1:13,1 of 20,2 of 2,4 of 5,6 of 26,0 of 0,1 of 1
1,Waldo Cortes Acosta,1,0,7 of 23,8 of 24,0 of 0,0,0:00,5 of 20,0 of 0,2 of 3,7 of 23,0 of 0,0 of 0
2,Curtis Blaydes,2,0,9 of 24,16 of 31,2 of 3,0,1:27,3 of 18,1 of 1,5 of 5,9 of 24,0 of 0,0 of 0
3,Waldo Cortes Acosta,2,0,9 of 36,9 of 36,0 of 0,0,0:00,7 of 34,0 of 0,2 of 2,9 of 36,0 of 0,0 of 0
4,Curtis Blaydes,3,0,8 of 23,9 of 24,1 of 4,0,0:58,1 of 12,1 of 2,6 of 9,8 of 23,0 of 0,0 of 0
5,Waldo Cortes Acosta,3,0,12 of 36,13 of 37,0 of 0,0,0:00,9 of 33,0 of 0,3 of 3,12 of 36,0 of 0,0 of 0

In [109]:
def parse_landed_attempted(value):
    landed, attempted = value.split(" of ")
    return int(landed), int(attempted)


validation_rows = []

for _, row in round_stats_df.iterrows():
    sig_landed, sig_attempted = parse_landed_attempted(
        row["significantStrikes"]
    )

    head_landed, head_attempted = parse_landed_attempted(row["head"])
    body_landed, body_attempted = parse_landed_attempted(row["body"])
    leg_landed, leg_attempted = parse_landed_attempted(row["leg"])

    distance_landed, distance_attempted = parse_landed_attempted(
        row["distance"]
    )
    clinch_landed, clinch_attempted = parse_landed_attempted(row["clinch"])
    ground_landed, ground_attempted = parse_landed_attempted(row["ground"])

    validation_rows.append({
        "fighter": row["fighterName"],
        "round": row["round"],
        "target_landed_matches": (
            head_landed + body_landed + leg_landed == sig_landed
        ),
        "target_attempted_matches": (
            head_attempted + body_attempted + leg_attempted == sig_attempted
        ),
        "position_landed_matches": (
            distance_landed + clinch_landed + ground_landed == sig_landed
        ),
        "position_attempted_matches": (
            distance_attempted
            + clinch_attempted
            + ground_attempted
            == sig_attempted
        ),
    })

validation_df = pd.DataFrame(validation_rows)
validation_df

,fighter,round,target_landed_matches,target_attempted_matches,position_landed_matches,position_attempted_matches
0,Curtis Blaydes,1,True,True,True,True
1,Waldo Cortes Acosta,1,True,True,True,True
2,Curtis Blaydes,2,True,True,True,True
3,Waldo Cortes Acosta,2,True,True,True,True
4,Curtis Blaydes,3,True,True,True,True
5,Waldo Cortes Acosta,3,True,True,True,True

### Cito API Validation Conclusion

Cito was successfully queried from Python using an API key stored outside
the repository.

Initial validation found:

- fighter search returns structured fighter IDs and profile data
- Cito provides newer fighter information than the historical Kaggle snapshot
- overlapping fighter attributes generally agree across sources
- some career aggregates differ because the sources represent different points
  in time or use slightly different source values
- Cito exposes event, bout, and true round-level statistics
- historical round-stat access is restricted by API plan
- recent round-stat data was successfully retrieved
- a three-round fight returned six records: one fighter-round record per fighter
  per round
- head/body/leg and distance/clinch/ground breakdowns reconciled exactly with
  significant-strike totals for every tested round

Cito appears useful as a current-data and round-stat provider, but provider data
should still be validated and normalized before being used by UPSET.

In [110]:
import json

# Find the specific fight in the response we previously fetched.
raw_bout = next(
    bout
    for bout in bouts_data["data"]
    if str(bout["id"]) == "12975"
)

# Display every field, including the nested fighter information.
print(json.dumps(raw_bout, indent=2))

{
  "id": "12975",
  "eventSlug": "ufc-fight-night-september-12-2026",
  "cardSection": "Main Card",
  "cardSectionOrder": 1,
  "cardPosition": "Main Card 5",
  "boutOrder": 1005,
  "weightClass": "Heavyweight",
  "titleBout": false,
  "status": "completed",
  "isCancelled": false,
  "cancellationReason": null,
  "winnerFighterSlug": "curtis-blaydes",
  "resultRound": 3,
  "resultTime": "5:00",
  "method": "Decision - Unanimous",
  "methodDetails": null,
  "odds": {
    "red": null,
    "blue": null
  },
  "awards": null,
  "dataAvailability": {
    "result": "available",
    "warning": "Using cached data",
    "warnings": [],
    "fetchedAt": "2026-09-16T07:10:13.833Z",
    "roundStats": "when_available",
    "dataAgeHours": 14.15,
    "dataFreshness": "live",
    "fighterCorners": "available"
  },
  "createdAt": "2026-08-05T20:15:47.125Z",
  "lastSyncedAt": "2026-09-16T21:16:20.122Z",
  "fighters": [
    {
      "id": "d29440ca-edfb-4877-9acc-611b85ebc874",
      "boutId": "12975",
      "fighterSlug": "curtis-blaydes",
      "fighterName": "Curtis Blaydes",
      "corner": "blue",
      "outcome": "win",
      "rankText": null,
      "country": "United States",
      "odds": null,
      "imageUrl": "https://ufc.com/images/styles/event_fight_card_upper_body_of_standing_athlete/s3/2026-09/BLAYDES_CURTIS_R_09-12.png?itok=hrU5rCtK",
      "fighterId": "ffbb498d-8144-48d7-bd5b-dc02b94c9e6e",
      "flag": "\ud83c\uddfa\ud83c\uddf8",
      "championStatus": "none",
      "profile": {
        "id": "ffbb498d-8144-48d7-bd5b-dc02b94c9e6e",
        "slug": "curtis-blaydes",
        "name": "Curtis Blaydes",
        "nickname": "Razor",
        "championStatus": "none",
        "division": "Heavyweight",
        "recordText": "20-6-0 (W-L-D)",
        "record": {
          "wins": 20,
          "losses": 6,
          "draws": 0,
          "noContest": null,
          "text": "20-6-0 (W-L-D)"
        },
        "country": "United States",
        "flag": "\ud83c\uddfa\ud83c\uddf8",
        "headshotUrl": "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-04/BLAYDES_CURTIS_04-11.png?itok=et0H5qDF",
        "imageUrl": "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-04/BLAYDES_CURTIS_04-11.png?itok=et0H5qDF",
        "bodyImageUrl": "https://ufc.com/images/styles/athlete_bio_full_body/s3/2026-04/BLAYDES_CURTIS_L_04-11.png?itok=Qv7hfvDn",
        "status": "Active",
        "isActive": true,
        "dataFreshness": "2026-09-16T15:23:40.579Z",
        "freshnessStatus": "live",
        "dataAgeHours": 5.92,
        "dataSource": null,
        "warning": null
      }
    },
    {
      "id": "b43735b4-1329-4b5a-817a-2bf09cc58e31",
      "boutId": "12975",
      "fighterSlug": "waldo-cortes-acosta",
      "fighterName": "Waldo Cortes Acosta",
      "corner": "red",
      "outcome": "loss",
      "rankText": null,
      "country": "Dominican Republic",
      "odds": null,
      "imageUrl": "https://ufc.com/images/styles/event_fight_card_upper_body_of_standing_athlete/s3/2026-09/CORTES_ACOSTA_WALDO_L_09-12.png?itok=xe7OyefZ",
      "fighterId": "ae6aa622-1b62-4cac-ab64-9179aa9f07af",
      "flag": "\ud83c\udde9\ud83c\uddf4",
      "championStatus": "none",
      "profile": {
        "id": "ae6aa622-1b62-4cac-ab64-9179aa9f07af",
        "slug": "waldo-cortes-acosta",
        "name": "Waldo Cortes Acosta",
        "nickname": "Salsa Boy",
        "championStatus": "none",
        "division": "Heavyweight",
        "recordText": "17-4-0 (W-L-D)",
        "record": {
          "wins": 17,
          "losses": 4,
          "draws": 0,
          "noContest": null,
          "text": "17-4-0 (W-L-D)"
        },
        "country": "Dominican Republic",
        "flag": "\ud83c\udde9\ud83c\uddf4",
        "headshotUrl": "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/CORTES_ACOSTA_WALDO_05-09.png?itok=ZhKHj1zg",
        "imageUrl": "https://ufc.com/images/styles/event_results_athlete_headshot/s3/2026-05/CORTES_ACOSTA_WALDO_05-09.png?itok=ZhKHj1zg",
        "bodyImageUrl": "https://ufc.com/images/styles/athlete_bio_full_body/s3/2026-05/CORTES_ACOSTA_WALDO_L.png?itok=agfAljgN",
        "status": "Active",
        "isActive": true,
        "dataFreshness": "2026-09-16T15:23:16.532Z",
        "freshnessStatus": "live",
        "dataAgeHours": 5.93,
        "dataSource": null,
        "warning": null
      }
    }
  ],
  "roundStats": [
    {
      "id": "e5dfafc4-b92e-40fc-b955-ebeb0f310cff",
      "boutId": "12975",
      "fighterSlug": "curtis-blaydes",
      "fighterName": "Curtis Blaydes",
      "round": 1,
      "knockdowns": 0,
      "significantStrikes": "7 of 27",
      "totalStrikes": "7 of 27",
      "takedowns": "1 of 3",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "1:13",
      "head": "1 of 20",
      "body": "2 of 2",
      "leg": "4 of 5",
      "distance": "6 of 26",
      "clinch": "0 of 0",
      "ground": "1 of 1",
      "lastSyncedAt": "2026-09-12T22:57:42.270Z"
    },
    {
      "id": "008a0327-ea88-42b4-853f-ec6974243fd2",
      "boutId": "12975",
      "fighterSlug": "waldo-cortes-acosta",
      "fighterName": "Waldo Cortes Acosta",
      "round": 1,
      "knockdowns": 0,
      "significantStrikes": "7 of 23",
      "totalStrikes": "8 of 24",
      "takedowns": "0 of 0",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "0:00",
      "head": "5 of 20",
      "body": "0 of 0",
      "leg": "2 of 3",
      "distance": "7 of 23",
      "clinch": "0 of 0",
      "ground": "0 of 0",
      "lastSyncedAt": "2026-09-12T22:57:41.682Z"
    },
    {
      "id": "74591e23-3fcf-4770-b3c8-2940a45122eb",
      "boutId": "12975",
      "fighterSlug": "waldo-cortes-acosta",
      "fighterName": "Waldo Cortes Acosta",
      "round": 2,
      "knockdowns": 0,
      "significantStrikes": "9 of 36",
      "totalStrikes": "9 of 36",
      "takedowns": "0 of 0",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "0:00",
      "head": "7 of 34",
      "body": "0 of 0",
      "leg": "2 of 2",
      "distance": "9 of 36",
      "clinch": "0 of 0",
      "ground": "0 of 0",
      "lastSyncedAt": "2026-09-12T22:57:41.889Z"
    },
    {
      "id": "47be510d-e7fa-4aac-9caa-6b3cddc8ab5f",
      "boutId": "12975",
      "fighterSlug": "curtis-blaydes",
      "fighterName": "Curtis Blaydes",
      "round": 2,
      "knockdowns": 0,
      "significantStrikes": "9 of 24",
      "totalStrikes": "16 of 31",
      "takedowns": "2 of 3",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "1:27",
      "head": "3 of 18",
      "body": "1 of 1",
      "leg": "5 of 5",
      "distance": "9 of 24",
      "clinch": "0 of 0",
      "ground": "0 of 0",
      "lastSyncedAt": "2026-09-12T22:57:42.465Z"
    },
    {
      "id": "cfcd80a1-a849-4416-97b0-0f7dc6a6bcb1",
      "boutId": "12975",
      "fighterSlug": "curtis-blaydes",
      "fighterName": "Curtis Blaydes",
      "round": 3,
      "knockdowns": 0,
      "significantStrikes": "8 of 23",
      "totalStrikes": "9 of 24",
      "takedowns": "1 of 4",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "0:58",
      "head": "1 of 12",
      "body": "1 of 2",
      "leg": "6 of 9",
      "distance": "8 of 23",
      "clinch": "0 of 0",
      "ground": "0 of 0",
      "lastSyncedAt": "2026-09-12T22:57:42.665Z"
    },
    {
      "id": "26e81f6d-0100-432f-bee4-c53a494e82cb",
      "boutId": "12975",
      "fighterSlug": "waldo-cortes-acosta",
      "fighterName": "Waldo Cortes Acosta",
      "round": 3,
      "knockdowns": 0,
      "significantStrikes": "12 of 36",
      "totalStrikes": "13 of 37",
      "takedowns": "0 of 0",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "0:00",
      "head": "9 of 33",
      "body": "0 of 0",
      "leg": "3 of 3",
      "distance": "12 of 36",
      "clinch": "0 of 0",
      "ground": "0 of 0",
      "lastSyncedAt": "2026-09-12T22:57:42.080Z"
    }
  ],
  "dataId": "12975",
  "hasStats": true,
  "referee": {
    "id": "20",
    "name": "Dan Miragliotta",
    "firstName": "Dan",
    "lastName": "Miragliotta"
  },
  "dataFreshness": "2026-09-16T07:10:13.833Z",
  "freshnessStatus": "live",
  "dataAgeHours": 14.15,
  "dataSource": null,
  "warning": null,
  "boutStats": [
    {
      "id": "63fe1d27-0376-4927-b4af-552cd9543de3",
      "boutId": "12975",
      "fighterSlug": "curtis-blaydes",
      "fighterName": "Curtis Blaydes",
      "knockdowns": 0,
      "significantStrikes": "24 of 74",
      "totalStrikes": "32 of 82",
      "takedowns": "4 of 10",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "3:38",
      "head": null,
      "body": null,
      "leg": null,
      "distance": null,
      "clinch": null,
      "ground": null,
      "lastSyncedAt": "2026-09-12T22:11:05.550Z"
    },
    {
      "id": "3b29d7e8-442f-4099-9efe-3904e0480fb6",
      "boutId": "12975",
      "fighterSlug": "waldo-cortes-acosta",
      "fighterName": "Waldo Cortes Acosta",
      "knockdowns": 0,
      "significantStrikes": "28 of 95",
      "totalStrikes": "30 of 97",
      "takedowns": "0 of 0",
      "submissionAttempts": 0,
      "reversals": 0,
      "controlTime": "0:00",
      "head": null,
      "body": null,
      "leg": null,
      "distance": null,
      "clinch": null,
      "ground": null,
      "lastSyncedAt": "2026-09-12T22:11:05.550Z"
    }
  ]
}

In [111]:
for index, fighter in enumerate(raw_bout["fighters"], start=1):
    print(f"\nFighter {index}")

    for key, value in fighter.items():
        if isinstance(value, (dict, list)):
            print(f"  {key}: [nested information]")
        else:
            print(f"  {key}: {value}")

Fighter 1
  id: d29440ca-edfb-4877-9acc-611b85ebc874
  boutId: 12975
  fighterSlug: curtis-blaydes
  fighterName: Curtis Blaydes
  corner: blue
  outcome: win
  rankText: None
  country: United States
  odds: None
  imageUrl: https://ufc.com/images/styles/event_fight_card_upper_body_of_standing_athlete/s3/2026-09/BLAYDES_CURTIS_R_09-12.png?itok=hrU5rCtK
  fighterId: ffbb498d-8144-48d7-bd5b-dc02b94c9e6e
  flag: 🇺🇸
  championStatus: none
  profile: [nested information]

Fighter 2
  id: b43735b4-1329-4b5a-817a-2bf09cc58e31
  boutId: 12975
  fighterSlug: waldo-cortes-acosta
  fighterName: Waldo Cortes Acosta
  corner: red
  outcome: loss
  rankText: None
  country: Dominican Republic
  odds: None
  imageUrl: https://ufc.com/images/styles/event_fight_card_upper_body_of_standing_athlete/s3/2026-09/CORTES_ACOSTA_WALDO_L_09-12.png?itok=xe7OyefZ
  fighterId: ae6aa622-1b62-4cac-ab64-9179aa9f07af
  flag: 🇩🇴
  championStatus: none
  profile: [nested information]

In [112]:
import importlib

from upset.data import normalization

# Reload so this notebook sees the function you just saved.
importlib.reload(normalization)

fight = normalization.normalize_cito_fight(raw_bout)

print("Bout ID:", fight.source_bout_id)
print("Fighter 1:", fight.fighter_1_name)
print("Fighter 1 ID:", fight.source_fighter_1_id)
print("Fighter 2:", fight.fighter_2_name)
print("Fighter 2 ID:", fight.source_fighter_2_id)
print("Winner:", fight.winner_name)
print("Method:", fight.result_method)
print("Round:", fight.result_round)
print("Time:", fight.result_time)

Bout ID: 12975
Fighter 1: Curtis Blaydes
Fighter 1 ID: ffbb498d-8144-48d7-bd5b-dc02b94c9e6e
Fighter 2: Waldo Cortes Acosta
Fighter 2 ID: ae6aa622-1b62-4cac-ab64-9179aa9f07af
Winner: Curtis Blaydes
Method: Decision - Unanimous
Round: 3
Time: 5:00

In [115]:
# Find the event whose slug matches the fight's eventSlug.
raw_event = next(
    event_record
    for event_record in recent_data["data"]
    if event_record["slug"] == raw_bout["eventSlug"]
)

# Convert the event into UPSET's format.
event = normalization.normalize_cito_event(raw_event)

# Convert the fight and attach the verified event ID.
fight = normalization.normalize_cito_fight(raw_bout, event=event)

print("Event:", event.title)
print("Date:", event.event_date)
print("Event ID:", event.source_event_id)
print("Fight's event ID:", fight.source_event_id)

assert fight.source_event_id == event.source_event_id
print("Event connection verified.")

Event: Noche UFC
Date: 2026-09-12
Event ID: af7fb97f-bc2a-440b-abdc-b03d4228bf44
Fight's event ID: af7fb97f-bc2a-440b-abdc-b03d4228bf44
Event connection verified.